title : tis be 2012
tagline: armageddon outta here
author :
  name : Oliver Scott
  email : os@koept.net
  github : oscott
  twitter : digitisation
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
